POST http://localhost:3001/api/exams/
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImRlbW91c2VyIiwiaWQiOiI2MTg4YmFiMTYwZjVjMjQzYjY2YTU3NzkiLCJpYXQiOjE2MzYzODI4NDUsImV4cCI6MTYzNjU5ODg0NX0.7Bk5MZ5yaN2fjucywBPsQ742CsnDyBytEXLPjj4Co9Y

{
   "subject": "Eco tut",
    "date": "10/11/2021",
    "syllabus": "Chapter 2"
}
