POST http://localhost:3001/api/exams/
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkJlY2siLCJpZCI6IjYxNzFhOWQ4ZGU4OTI4OWYxM2ZlNDUyYSIsImlhdCI6MTYzNTYwMTI4NCwiZXhwIjoxNjM1ODE3Mjg0fQ.MM7gEDr7c2n4bbxwWdsgC-uDrkpmQF24wHnyEFSsZKY

{
   "subject": "New exam",
    "date": "5/11/2021",
    "syllabus": "Chapter 5"
}
