POST http://localhost:3001/api/exams/
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkJlY2siLCJpZCI6IjYxNzFhOWQ4ZGU4OTI4OWYxM2ZlNDUyYSIsImlhdCI6MTYzNTk2MTk3NiwiZXhwIjoxNjM2MTc3OTc2fQ.9eaJMNFLSoxcaAc3sTATH4TdwYB9vd3kX4t0KoBgm4U

{
   "subject": "New exam 2",
    "date": "5/11/2021",
    "syllabus": "Chapter 5"
}
